<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */

/** @var $block View */

/** @var $escaper Escaper */


use Magento\Catalog\Block\Product\View;
use Magento\Framework\Escaper;

?>
<?php $_product = $block->getProduct(); ?>
<?php $buttonTitle = __('Add to Cart'); ?>
<?php if ($_product->isSaleable()) : ?>
    <div class="box-tocart">
        <div class="fieldset">
            <?php if ($block->shouldRenderQuantity()) : ?>
                <div class="field qty">
                    <label class="label" for="qty"><span><?= $escaper->escapeHtml(__('5 Qty')) ?></span></label>
                    <div class="control">


                        <input type="radio"
                               name="qty"
                               id="qty"

                               value="5"
                               title="<?= $escaper->escapeHtmlAttr(__('5 Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $escaper->escapeHtml(json_encode($block->getQuantityValidators())) ?>"

                        >


                    </div>
                    <label class="label" for="qty"><span><?= $escaper->escapeHtml(__('10 Qty')) ?></span></label>
                    <div class="control">

                        <input type="checkbox"
                               name="qty"
                               id="qty"
                               value="10"
                               title="<?= $escaper->escapeHtmlAttr(__('10 Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $escaper->escapeHtml(json_encode($block->getQuantityValidators())) ?>"

                        >

                    </div>
                    <label class="label" for="qty"><span><?= $escaper->escapeHtml(__('20 Qty')) ?></span></label>
                    <div class="control">


                        <input type="checkbox"
                               name="qty"
                               id="qty"
                               value="20"
                               title="<?= $escaper->escapeHtmlAttr(__('20 Qty')) ?>"
                               class="input-text qty"
                               data-validate="<?= $escaper->escapeHtml(json_encode($block->getQuantityValidators())) ?>"

                        >

                    </div>
                </div>
            <?php endif; ?>
            <div class="actions">
                <button type="submit"
                        title="<?= $escaper->escapeHtmlAttr($buttonTitle) ?>"
                        class="action primary tocart"
                        id="product-addtocart-button" disabled>
                    <span><?= $escaper->escapeHtml($buttonTitle) ?></span>
                </button>
                <?= $block->getChildHtml('', true) ?>
            </div>
        </div>
    </div>
<?php endif; ?>
<script type="text/x-magento-init">
    {
        "#product_addtocart_form": {
            "Magento_Catalog/js/validate-product": {}
        }
    }





</script>

